# Generated by Django 5.0 on 2023-12-15 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_product_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEliminado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_compra', models.DateField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fkproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
