# Generated by Django 5.0 on 2023-12-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productoeliminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoeliminado',
            name='fkproducto',
        ),
        migrations.AlterField(
            model_name='productoeliminado',
            name='fecha_compra',
            field=models.DateField(),
        ),
    ]
